[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This ensures your functions are treated as API endpoints
[functions]
  node_bundler = "esbuild"
